# CAD AI Studio - Default Agent Rules
# This file configures how the AI generates CadQuery code
# Users can customize this to improve accuracy for their use cases

version: 1

# =============================================================================
# COORDINATE SYSTEM
# =============================================================================
coordinate_system:
  description: "Right-hand coordinate system"
  x:
    direction: "length / front-back"
    positive: "forward"
  y:
    direction: "width / left-right"
    positive: "right"
  z:
    direction: "height / up-down"
    positive: "up"
  origin: "center of bottom face (unless specified)"

# =============================================================================
# SPATIAL REASONING RULES
# =============================================================================
spatial_rules:
  before_any_operation:
    - "Mentally visualize the current state of the model"
    - "Identify which faces/edges the operation targets"
    - "Verify operation will intersect existing geometry"

  boolean_cut:
    - "The cutting tool MUST overlap the target body"
    - "Position cutting tool so it extends BEYOND the target surface"
    - "Use .cut() or .cutBlind() with sufficient depth"

  boolean_fuse:
    - "Bodies MUST touch or overlap to fuse"
    - "Verify no air gap between bodies"

  extrude:
    - "Positive height = extrude in +Z direction"
    - "Negative height = extrude in -Z direction"
    - "Always specify direction explicitly if not along Z"

  sketch_placement:
    - "XY plane = floor (Z=0)"
    - "XZ plane = front wall (Y=0)"
    - "YZ plane = side wall (X=0)"
    - "Use .faces('>Z') to select top face for next operation"
    - "Use .faces('<Z') to select bottom face"

  natural_language_to_axis:
    - "upper / lower / top / bottom / above / below → Z axis"
    - "left / right → Y axis"
    - "front / back / forward / backward → X axis"
    - "taller / shorter → Z dimension"
    - "wider / narrower → Y dimension"
    - "longer / shorter (depth) → X dimension"

  splitting_and_halving:
    - "CRITICAL: 'cut in half' means bisect the object along the CENTER of the relevant axis"
    - "'top half' / 'upper half' / 'bottom half' / 'lower half' → split on XY plane at Z midpoint"
    - "'left half' / 'right half' → split on XZ plane at Y midpoint"
    - "'front half' / 'back half' → split on YZ plane at X midpoint"
    - "PREFERRED METHOD — use boolean intersection with a box:"
    - "  Lower half: sphere.intersect(cq.Workplane('XY').box(R*3, R*3, R).translate((0,0,-R/2)))"
    - "  Upper half: sphere.intersect(cq.Workplane('XY').box(R*3, R*3, R).translate((0,0,R/2)))"
    - "ALTERNATIVE — use .split() (less reliable): .workplane(offset=0).split(keepBottom=True)"
    - "COMMON MISTAKE: Do NOT split along X or Y when the user says 'top/bottom' — that produces a vertical D-shape, not a horizontal hemisphere"
    - "For a sphere centered at origin, 'lower half' = everything with Z < 0, 'upper half' = everything with Z > 0"

  face_selectors:
    - "'>Z' = topmost face (highest Z value)"
    - "'<Z' = bottommost face (lowest Z value)"
    - "'>Y' = rightmost face"
    - "'<Y' = leftmost face"
    - "'>X' = front face (furthest forward)"
    - "'<X' = back face (furthest backward)"

# =============================================================================
# CADQUERY CODE REQUIREMENTS
# =============================================================================
code_requirements:
  mandatory:
    - "Always import cadquery as cq"
    - "Final result MUST be assigned to variable named 'result'"
    - "Use CadQuery's fluent API (method chaining)"
    - "All dimensions in millimeters"

  forbidden:
    - "Do NOT use show_object() or display()"
    - "Do NOT use cq.exporters directly — the runner handles export"
    - "Do NOT use matplotlib or any GUI libraries"
    - "Do NOT read/write files"

# =============================================================================
# VALIDATION CHECKS
# =============================================================================
validation:
  pre_generation:
    - check: "dimensions_realistic"
      rule: "All dimensions between 0.1mm and 10000mm"
      on_fail: "Ask user to confirm unusual dimensions"

    - check: "wall_thickness"
      rule: "Minimum wall thickness >= 0.5mm for 3D printing"
      on_fail: "Warn user about thin walls"

    - check: "cut_intersects"
      rule: "All cut operations must intersect target body"
      on_fail: "Recalculate cut position"

  post_generation:
    - check: "mesh_watertight"
      rule: "Generated mesh must be manifold"
      on_fail: "Report error, suggest fixes"

    - check: "no_self_intersection"
      rule: "No self-intersecting geometry"
      on_fail: "Simplify operations, rebuild step by step"

# =============================================================================
# ERROR HANDLING
# =============================================================================
on_error:
  spatial_confusion:
    - "STOP - do not guess"
    - "Draw ASCII diagram showing X, Y, Z axes"
    - "List current body bounds: min/max for each axis"
    - "Calculate exact coordinates for intended operation"
    - "Verify calculation before generating code"

  cadquery_error:
    - "Read the Python traceback carefully"
    - "Identify which CadQuery operation failed"
    - "Check face/edge selectors are valid"
    - "Verify the workplane is correct"
    - "Fix and regenerate the complete code"

  general:
    - "Explain what went wrong in plain language"
    - "Show the problematic code section"
    - "Propose specific fix with reasoning"
    - "Ask user to confirm before applying"

# =============================================================================
# CODE GENERATION STYLE
# =============================================================================
code_style:
  naming:
    - "Use descriptive variable names: 'bolt_hole_dia' not 'd1'"
    - "Use UPPER_CASE for dimension constants"
    - "Use lowercase for intermediate results"

  comments:
    - "Comment the INTENT, not the operation"
    - "Example: '# Hole for M5 bolt' not '# Make circle'"

  organization:
    - "Define dimensions as named constants at top"
    - "Group related operations"
    - "Use intermediate variables for complex geometry"

  example: |
    import cadquery as cq

    # Mounting bracket for sensor
    # Designed for 3D printing in PLA/PETG

    THICKNESS = 3.0      # mm - wall thickness
    BOLT_HOLE_DIA = 5.5  # mm - clearance for M5
    WIDTH = 40.0         # mm
    DEPTH = 30.0         # mm

    result = (
        cq.Workplane("XY")
        .box(WIDTH, DEPTH, THICKNESS)
        # Mounting holes for M5 bolts
        .faces(">Z")
        .workplane()
        .pushPoints([(15, 10), (15, -10)])
        .hole(BOLT_HOLE_DIA)
    )

# =============================================================================
# MANUFACTURING AWARENESS
# =============================================================================
manufacturing:
  3d_printing:
    min_wall: 0.8           # mm
    min_hole_diameter: 2.0  # mm
    max_overhang: 45        # degrees without support
    layer_height_typical: 0.2  # mm

  cnc_milling:
    min_internal_radius: 1.5  # mm (tool radius)
    min_pocket_depth_ratio: 3 # depth / width

  laser_cutting:
    min_slot_width: 1.0     # mm
    kerf_typical: 0.2       # mm

# =============================================================================
# RESPONSE FORMAT
# =============================================================================
response_format:
  on_success:
    - "Brief description of what was created"
    - "The generated CadQuery code in a ```python block"
    - "Any warnings or suggestions"

  on_clarification_needed:
    - "Explain what information is missing"
    - "Provide 2-3 specific options to choose from"
    - "Default suggestion if user doesn't specify"

  never:
    - "Never generate code for ambiguous requests without asking"
    - "Never assume dimensions - always ask if not specified"
    - "Never skip validation steps"

# =============================================================================
# CADQUERY COOKBOOK - REFERENCE PATTERNS
# =============================================================================
# Use these as reference for correct CadQuery API usage.
# Each recipe is a self-contained working example.

cookbook:
  - title: "Hollow box (shell operation)"
    description: "Create a box and shell it to make a container with uniform wall thickness"
    code: |
      import cadquery as cq
      W, D, H = 60.0, 40.0, 30.0
      WALL = 2.0
      result = (
          cq.Workplane("XY")
          .box(W, D, H)
          .faces(">Z")
          .shell(-WALL)
      )

  - title: "Through-cut slot on a wall face"
    description: "Select a specific face and cut a slot that goes all the way through"
    code: |
      import cadquery as cq
      W, D, H = 60.0, 40.0, 30.0
      SLOT_W, SLOT_H = 20.0, 10.0
      result = (
          cq.Workplane("XY")
          .box(W, D, H)
          # Select the front face (+X), place workplane, cut through
          .faces(">X")
          .workplane()
          .rect(SLOT_W, SLOT_H)
          .cutThruAll()
      )

  - title: "Opposing through-slots on two walls"
    description: "Cut matching slots on opposite faces - e.g. entry ports on both short sides of a box"
    code: |
      import cadquery as cq
      W, D, H = 80.0, 40.0, 30.0
      WALL = 2.0
      SLOT_W, SLOT_H = 20.0, 12.0
      # Start with a hollow box
      box = (
          cq.Workplane("XY")
          .box(W, D, H)
          .faces(">Z")
          .shell(-WALL)
      )
      # Cut slot on front face (+X)
      box = (
          box.faces(">X")
          .workplane()
          .rect(SLOT_W, SLOT_H)
          .cutThruAll()
      )
      # Cut slot on back face (-X)
      result = (
          box.faces("<X")
          .workplane()
          .rect(SLOT_W, SLOT_H)
          .cutThruAll()
      )

  - title: "Fillets and chamfers on specific edges"
    description: "Apply fillets or chamfers to selected edges using edge selectors"
    code: |
      import cadquery as cq
      W, D, H = 50.0, 30.0, 20.0
      result = (
          cq.Workplane("XY")
          .box(W, D, H)
          # Fillet only the top edges
          .edges(">Z")
          .fillet(2.0)
          # Chamfer only the bottom edges
          .edges("<Z")
          .chamfer(1.0)
      )

  - title: "Pattern of holes (pushPoints)"
    description: "Create multiple holes at specific positions using pushPoints"
    code: |
      import cadquery as cq
      W, D, H = 80.0, 60.0, 5.0
      HOLE_DIA = 5.5
      # Hole positions as (x, y) tuples on the top face
      HOLE_POS = [(30, 20), (-30, 20), (30, -20), (-30, -20)]
      result = (
          cq.Workplane("XY")
          .box(W, D, H)
          .faces(">Z")
          .workplane()
          .pushPoints(HOLE_POS)
          .hole(HOLE_DIA)
      )

  - title: "Boolean operations (cut, union, intersect)"
    description: "Combine two bodies using boolean cut, union, or intersect"
    code: |
      import cadquery as cq
      # Base plate
      plate = cq.Workplane("XY").box(60, 40, 5)
      # Cylinder to add on top
      boss = cq.Workplane("XY").workplane(offset=5).circle(10).extrude(15)
      # Hole to subtract
      hole = cq.Workplane("XY").circle(4).extrude(20)
      # Union the boss onto the plate, then cut the hole
      result = plate.union(boss).cut(hole)

  - title: "Workplane switching and offsets"
    description: "Work on different planes and at offsets from existing geometry"
    code: |
      import cadquery as cq
      BASE_H = 10.0
      # Base on XY plane
      base = cq.Workplane("XY").box(40, 40, BASE_H)
      # Switch to top face and extrude a smaller block upward
      result = (
          base.faces(">Z")
          .workplane()
          .rect(20, 20)
          .extrude(15)
      )

  - title: "Concentric circles for tubes and rings"
    description: "Create a tube or ring using concentric circles"
    code: |
      import cadquery as cq
      OUTER_R = 20.0
      INNER_R = 16.0
      HEIGHT = 30.0
      result = (
          cq.Workplane("XY")
          .circle(OUTER_R)
          .circle(INNER_R)
          .extrude(HEIGHT)
      )
